import 'package:flutter/painting.dart';
import 'package:random_color/random_color.dart';

class Child1 {
  final String head;
  final String lable;
  final Color color = RandomColor().randomColor();
  final List children;
  Child1(this.head, this.lable, this.children);
}

class Child3 {
  Child3();
  String label;
  String uid;
  String url;
  String productUrl;

  factory Child3.fromJson(json) {
    Child3 child3 = Child3();
    child3.label = json['bookName'];
    child3.url = json['imageUrl'];
    child3.uid = json['uid'];
    child3.productUrl = json['productUrl'];
    return child3;
  }
}

List englishChildrenList = [
  [
    Child2("M", "Maths", "english/12/maths"),
    Child2("P", "Physics", "english/12/physics"),
    Child2("A", "Accountancy", "english/12/accountancy"),
    Child2("S", "Sanskrit", "english/12/sanskrit"),
    Child2("H", "Hindi", "english/12/hindi"),
    Child2("E", "English", "english/12/english"),
    Child2("B", "Biology", "english/12/biology"),
    Child2("H", "History", "english/12/history"),
    Child2("G", "Geography", "english/12/geography"),
    Child2("P", "Psychology", "english/12/psychology"),
    Child2("S", "Sociology", "english/12/sociology"),
    Child2("C", "Chemistry", "english/12/chemistry"),
    Child2("PS", "Political Science", "english/12/politicalScience"),
    Child2("E", "Economics", "english/12/economics"),
    Child2("BS", "Business Studies", "english/12/businessStudies"),
    Child2("H", "Heritage Crafts", "english/12/HeritageCrafts"),
    Child2("N", "New Age Graphics Design", "english/12/newAgeGraphicsDesign"),
    Child2("H", "Home Science", "english/12/homeScience"),
  ],
  [
    Child2("S", "Sanskrit", "english/11/sanskrit"),
    Child2("A", "Accountancy", "english/11/accountancy"),
    Child2("M", "Maths", "english/11/maths"),
    Child2("C", "Chemistry", "english/11/chemistry"),
    Child2("ST", "Statistics", "english/11/statistics"),
    Child2("B", "Biology", "english/11/biology"),
    Child2("P", "Psychology", "english/11/psychology"),
    Child2("G", "Geography", "english/11/geography"),
    Child2("P", "Physics", "english/11/physics"),
    Child2("H", "Hindi", "english/11/hindi"),
    Child2("S", "Sociology", "english/11/sociology"),
    Child2("E", "English", "english/11/english"),
    Child2("PS", "Political Science", "english/11/politicalScience"),
    Child2("H", "History", "english/11/history"),
    Child2("PS", "Political Science", "english/11/politicalScience"),
    Child2("H", "History", "english/11/history"),
    Child2("C", "Economics", "english/11/economics"),
    Child2("BS", "Business Studies", "english/11/businessStudies"),
    Child2("H", "Heritage Crafts", "english/11/HeritageCrafts"),
    Child2("G", "Graphics design", "english/11/graphicsDesign"),
    Child2("c", "CCT", "english/11/cct"),
    Child2("H", "Home Science", "english/11/homeScience"),
    Child2("C", "Creative Writing", "english/11/creativeWriting"),
    Child2("F", "Fine Art", "english/11/fineArt"),
    Child2("I", "Information Practices", "english/11/informationPractice"),
    Child2("C", "Computer Science", "english/11/computerScience")
  ],
  [
    Child2("M", "Maths", "english/10/maths"),
    Child2("S", "Science", "english/10/science"),
    Child2("E", "English", "english/10/english"),
    Child2("S", "Sanskrit", "english/10/sanskrit"),
    Child2("ST", "Social Studies", "english/10/socialStudies"),
    Child2("H", "Hindi", "english/10/hindi"),
  ],
  [
    Child2("M", "Maths", "english/9/maths"),
    Child2("S", "Science", "english/9/science"),
    Child2("E", "English", "english/9/english"),
    Child2("S", "Sanskrit", "english/9/sanskrit"),
    Child2("ST", "Social Studies", "english/9/socialStudies"),
    Child2("H", "Hindi", "english/9/hindi"),
    Child2("I", "Information Technology", "english/9/informationTechnology"),
    Child2("P", "Physical Education", "englisg/9/physicalEducation"),
  ],
  [
    Child2("M", "Maths", "english/8/maths"),
    Child2("S", "Science", "english/8/science"),
    Child2("E", "English", "english/8/english"),
    Child2("S", "Sanskrit", "english/8/sanskrit"),
    Child2("ST", "Social Studies", "english/8/socialStudies"),
    Child2("H", "Hindi", "english/8/hindi"),
  ],
  [
    Child2("M", "Maths", "english/7/maths"),
    Child2("S", "Science", "english/7/science"),
    Child2("E", "English", "english/7/english"),
    Child2("S", "Sanskrit", "english/7/sanskrit"),
    Child2("ST", "Social Studies", "english/7/socialStudies"),
    Child2("H", "Hindi", "english/7/hindi"),
  ],
  [
    Child2("M", "Maths", "english/6/maths"),
    Child2("S", "Science", "english/6/science"),
    Child2("E", "English", "english/6/english"),
    Child2("S", "Sanskrit", "english/6/sanskrit"),
    Child2("ST", "Social Studies", "english/6/socialStudies"),
    Child2("H", "Hindi", "english/6/hindi"),
  ],
  [
    Child2("M", "Maths", "english/5/maths"),
    Child2("H", "Hindi", "english/5/hindi"),
    Child2("EN", "Environmental", "english/5/environmental"),
    Child2("E", "English", "english/5/english"),
  ],
  [
    Child2("M", "Maths", "english/4/maths"),
    Child2("H", "Hindi", "english/4/hindi"),
    Child2("EN", "Environmental", "english/4/environmental"),
    Child2("E", "English", "english/4/english"),
  ],
  [
    Child2("M", "Maths", "english/3/maths"),
    Child2("H", "Hindi", "english/3/hindi"),
    Child2("EN", "Environmental", "english/3/environmental"),
    Child2("E", "English", "english/3/english"),
  ],
  [
    Child2("M", "Maths", "english/2/maths"),
    Child2("H", "Hindi", "english/2/hindi"),
    Child2("E", "English", "english/2/english"),
  ],
  [
    Child2("M", "Maths", "english/1/maths"),
    Child2("H", "Hindi", "english/1/hindi"),
    Child2("E", "English", "english/1/english"),
  ],
];

List hindiChildrenList = [
  [
    Child2("M", "Maths", "hindi/12/maths"),
    Child2("P", "Physics", "hindi/12/physics"),
    Child2("A", "Accountancy", "hindi/12/accountancy"),
    Child2("S", "Sanskrit", "hindi/12/sanskrit"),
    Child2("H", "Hindi", "hindi/12/hindi"),
    Child2("E", "English", "hindi/12/english"),
    Child2("B", "Biology", "hindi/12/biology"),
    Child2("H", "History", "hindi/12/history"),
    Child2("G", "Geography", "hindi/12/geography"),
    Child2("P", "Psychology", "hindi/12/psychology"),
    Child2("S", "Sociology", "hindi/12/sociology"),
    Child2("C", "Chemistry", "hindi/12/chemistry"),
    Child2("PS", "Political Science", "hindi/12/politicalScience"),
    Child2("E", "Economics", "hindi/12/economics"),
    Child2("BS", "Business Studies", "hindi/12/businessStudies"),
    Child2("H", "Heritage Crafts", "hindi/12/HeritageCrafts"),
    Child2("N", "New Age Graphics Design", "hindi/12/newAgeGraphicsDesign"),
    Child2("H", "Home Science", "hindi/12/homeScience"),
  ],
  [
    Child2("S", "Sanskrit", "hindi/11/sanskrit"),
    Child2("A", "Accountancy", "hindi/11/accountancy"),
    Child2("M", "Maths", "hindi/11/maths"),
    Child2("C", "Chemistry", "hindi/11/chemistry"),
    Child2("ST", "Statistics", "hindi/11/statistics"),
    Child2("B", "Biology", "hindi/11/biology"),
    Child2("P", "Psychology", "hindi/11/psychology"),
    Child2("G", "Geography", "hindi/11/geography"),
    Child2("P", "Physics", "hindi/11/physics"),
    Child2("H", "Hindi", "hindi/11/hindi"),
    Child2("S", "Sociology", "hindi/11/sociology"),
    Child2("E", "English", "hindi/11/english"),
    Child2("PS", "Political Science", "hindi/11/politicalScience"),
    Child2("H", "History", "hindi/11/history"),
    Child2("PS", "Political Science", "hindi/11/politicalScience"),
    Child2("H", "History", "hindi/11/history"),
    Child2("C", "Economics", "hindi/11/economics"),
    Child2("BS", "Business Studies", "hindi/11/businessStudies"),
    Child2("H", "Heritage Crafts", "hindi/11/HeritageCrafts"),
    Child2("G", "Graphics design", "hindi/11/graphicsDesign"),
    Child2("c", "CCT", "hindi/11/cct"),
    Child2("H", "Home Science", "hindi/11/homeScience"),
    Child2("C", "Creative Writing", "hindi/11/creativeWriting"),
    Child2("F", "Fine Art", "hindi/11/fineArt"),
    Child2("I", "Information Practices", "hindi/11/informationPractice"),
    Child2("C", "Computer Science", "hindi/11/computerScience")
  ],
  [
    Child2("M", "Maths", "hindi/10/maths"),
    Child2("S", "Science", "hindi/10/science"),
    Child2("E", "Engish", "hindi/10/english"),
    Child2("S", "Sanskrit", "hindi/10/sanskrit"),
    Child2("ST", "Social Studies", "hindi/10/socialStudies"),
    Child2("H", "Hindi", "hindi/10/hindi"),
  ],
  [
    Child2("M", "Maths", "hindi/9/maths"),
    Child2("S", "Science", "hindi/9/science"),
    Child2("E", "English", "hindi/9/english"),
    Child2("S", "Sanskrit", "hindi/9/sanskrit"),
    Child2("ST", "Social Studies", "hindi/9/socialStudies"),
    Child2("H", "Hindi", "hindi/9/hindi"),
    Child2("I", "Information Technology", "hindi/9/informationTechnology"),
    Child2("P", "Physical Education", "englisg/9/physicalEducation"),
  ],
  [
    Child2("M", "Maths", "hindi/8/maths"),
    Child2("S", "Science", "hindi/8/science"),
    Child2("E", "English", "hindi/8/english"),
    Child2("S", "Sanskrit", "hindi/8/sanskrit"),
    Child2("ST", "Social Studies", "hindi/8/socialStudies"),
    Child2("H", "Hindi", "hindi/8/hindi"),
  ],
  [
    Child2("M", "Maths", "hindi/7/maths"),
    Child2("S", "Science", "hindi/7/science"),
    Child2("E", "English", "hindi/7/english"),
    Child2("S", "Sanskrit", "hindi/7/sanskrit"),
    Child2("ST", "Social Studies", "hindi/7/socialStudies"),
    Child2("H", "Hindi", "hindi/7/hindi"),
  ],
  [
    Child2("M", "Maths", "hindi/6/maths"),
    Child2("S", "Science", "hindi/6/science"),
    Child2("E", "English", "hindi/6/english"),
    Child2("S", "Sanskrit", "hindi/6/sanskrit"),
    Child2("ST", "Social Studies", "hindi/6/socialStudies"),
    Child2("H", "Hindi", "hindi/6/hindi"),
  ],
  [
    Child2("M", "Maths", "hindi/5/maths"),
    Child2("H", "Hindi", "hindi/5/hindi"),
    Child2("EN", "Environmental", "hindi/5/environmental"),
    Child2("E", "English", "hindi/5/english"),
  ],
  [
    Child2("M", "Maths", "hindi/4/maths"),
    Child2("H", "Hindi", "hindi/4/hindi"),
    Child2("EN", "Environmental", "hindi/4/environmental"),
    Child2("E", "English", "hindi/4/english"),
  ],
  [
    Child2("M", "Maths", "hindi/3/maths"),
    Child2("H", "Hindi", "hindi/3/hindi"),
    Child2("EN", "Environmental", "hindi/3/environmental"),
    Child2("E", "English", "hindi/3/english"),
  ],
  [
    Child2("M", "Maths", "hindi/2/maths"),
    Child2("H", "Hindi", "hindi/2/hindi"),
    Child2("E", "English", "hindi/2/english"),
  ],
  [
    Child2("M", "Maths", "hindi/1/maths"),
    Child2("H", "Hindi", "hindi/1/hindi"),
    Child2("E", "English", "hindi/1/english"),
  ],
];

List solutionsChildrenList = [
  [
    Child2("11", "RS Aggarwal(XI)", "solution/RS/XI"),
    Child2("10", "RS Aggarwal(X)", "solution/RS/X"),
    Child2("9", "RS Aggarwal(IX)", "solution/RS/IX"),
    Child2("8", "RS Aggarwal(VIII)", "solution/RS/VIII"),
    Child2("7", "RS Aggarwal(VII)", "solution/RS/VII"),
    Child2("6", "RS Aggarwal(VI)", "solution/RS/VI"),
  ],
  [
    Child2("12", "RD Sharma(XII)", "solution/RD/XII"),
    Child2("11", "RD Sharma(XI)", "solution/RD/XI"),
    Child2("10", "RD Sharma(X)", "solution/RD/X"),
    Child2("9", "RD Sharma(IX)", "solution/RD/IX"),
    Child2("8", "RD Sharma(VIII)", "solution/RD/VIII"),
    Child2("7", "RD Sharma(VII)", "solution/RD/VII"),
    Child2("6", "RD Sharma(VI)", "solution/RD/VI"),
  ],
  [
    Child2("HC", "HC Verma(I)", "solution/HC/I"),
    Child2("HC", "HC Verma(II)", "solution/HC/II"),
  ],
  [Child2("IE", "All Solutions", "solution/IE/SS")],
  [
    Child2("C", "Chemistry Class(X)", "solution/LS/CX"),
    Child2("B", "Biology Class(X)", "solution/LS/PX"),
    Child2("P", "Physics Class(X)", "solution/LS/PX"),
    Child2("C", "Chemistry Class(XI)", "solution/LS/CIX"),
    Child2("B", "Biology Class(XI)", "solution/LS/BIX"),
    Child2("P", "Physics Class(XI)", "solution/LS/PIX"),
    Child2("S", "Science Class(VIII)", "solution/LS/SVIII"),
  ],
  [
    Child2("11", "Class(XI) Latest Edition(XI)", "solution/TS/L11"),
    Child2("12", "Class(XII) Latest Edition(XII)", "solution/TS/L12"),
    Child2("11", "Class(XI) Old Edition(XI)", "solution/TS/O11"),
    Child2("12", "Class(XII) Old Edition(XII)", "solution/TS/O12"),
  ],
  [
    Child2("M", "Maths Solutions", "solution/12/MS"),
    Child2("P", "Physics Solutions", "solution/12/PS"),
    Child2("A", "Accountancy Solutions", "solution/12/AS"),
    Child2("E", "English Solutions", "solution/12/ES"),
    Child2("B", "Biology Solutions", "solution/12/BS"),
    Child2("P", "Pyschology Solutions", "solution/12/PYS"),
    Child2("C", "Chemistry Solutions", "solution/12/CS"),
    Child2("E", "Economics Solutions", "solution/12/ES"),
    Child2("BS", "Business Studies \nSolutions", "solution/12/BSS"),
    Child2("H", "History Solutions", "solution/12/HS"),
    Child2("PS", "Political Science \nSolutions", "solution/12/PSS"),
    Child2("S", "Sociology Solutions", "solution/12/SS"),
    Child2("H", "Hindi Solutions", "solution/12/HIS"),
    Child2("CS", "Computer Science\n Solutions", "solution/12/CSS"),
    Child2("G", "Geography Solutions", "solution/12/GS"),
  ],
  [
    Child2("M", "Maths Solutions", "solution/11/MS"),
    Child2("P", "Physics Solutions", "solution/11/PS"),
    Child2("A", "Accountancy Solutions", "solution/11/AS"),
    Child2("E", "English Solutions", "solution/11/ES"),
    Child2("B", "Biology Solutions", "solution/11/BS"),
    Child2("P", "Pyschology Solutions", "solution/11/PYS"),
    Child2("C", "Chemistry Solutions", "solution/11/CS"),
    Child2("E", "Economics Solutions", "solution/11/ES"),
    Child2("BS", "Business Studies \nSolutions", "solution/11/BSS"),
    Child2("H", "History Solutions", "solution/11/HS"),
    Child2("PS", "Political Science \nSolutions", "solution/11/PSS"),
    Child2("S", "Sociology Solutions", "solution/11/SS"),
    Child2("H", "Hindi Solutions", "solution/11/HIS"),
    Child2("CS", "Computer Science\n Solutions", "solution/11/CSS"),
    Child2("G", "Geography Solutions", "solution/11/GS"),
    Child2("ST", "Statistics Solutions", "solution/11/STS"),
  ],
  [
    Child2("M", "Maths Solutions", "solution/10/MS"),
    Child2("S", " Science Solutions", "solution/10/SS"),
    Child2("E", "English Solutions", "solution/10/ES"),
    Child2("ST", "Social Studies \nSolutions", "solution/10/SS"),
    Child2("H", "Hindi Solutions", "solution/10/HIS"),
    Child2("S", "Sanskrit Solutions", "solution/10/SNS"),
  ],
  [
    Child2("M", "Maths Solutions", "solution/9/MS"),
    Child2("S", " Science Solutions", "solution/9/SS"),
    Child2("E", "English Solutions", "solution/9/ES"),
    Child2("ST", "Social Studies \nSolutions", "solution/9/SS"),
    Child2("H", "Hindi Solutions", "solution/9/HIS"),
    Child2("S", "Sanskrit Solutions", "solution/9/SNS"),
  ],
  [
    Child2("M", "Maths Solutions", "solution/8/MS"),
    Child2("S", " Science Solutions", "solution/8/SS"),
    Child2("E", "English Solutions", "solution/8/ES"),
    Child2("ST", "Social Studies \nSolutions", "solution/8/SS"),
    Child2("H", "Hindi Solutions", "solution/8/HIS"),
    Child2("S", "Sanskrit Solutions", "solution/8/SNS"),
  ],
  [
    Child2("M", "Maths Solutions", "solution/7/MS"),
    Child2("S", " Science Solutions", "solution/7/SS"),
    Child2("E", "English Solutions", "solution/7/ES"),
    Child2("ST", "Social Studies \nSolutions", "solution/7/SS"),
    Child2("H", "Hindi Solutions", "solution/7/HIS"),
    Child2("S", "Sanskrit Solutions", "solution/7/SNS"),
  ],
  [
    Child2("M", "Maths Solutions", "solution/6/MS"),
    Child2("S", " Science Solutions", "solution/6/SS"),
    Child2("E", "English Solutions", "solution/6/ES"),
    Child2("ST", "Social Studies \nSolutions", "solution/6/SS"),
    Child2("H", "Hindi Solutions", "solution/6/HIS"),
    Child2("S", "Sanskrit Solutions", "solution/6/SNS"),
  ],
  [
    Child2("M", "Maths Solutions", "solution/5/MS"),
    Child2("S", " Science Solutions", "solution/5/SS"),
    Child2("E", "English Solutions", "solution/5/ES"),
    Child2("ST", "Social Studies \nSolutions", "solution/5/SS"),
    Child2("H", "Hindi Solutions", "solution/5/HIS"),
    Child2("S", "Sanskrit Solutions", "solution/5/SNS"),
  ],
  [
    Child2("M", "Maths Solutions", "solution/4/MS"),
    Child2("E", "English Solutions", "solution/4/ES"),
    Child2("EN", "Environmental Studies \nSolutions", "solution/4/ENS"),
    Child2("H", "Hindi Solutions", "solution/4/HIS"),
  ],
  [
    Child2("M", "Maths Solutions", "solution/3/MS"),
    Child2("E", "English Solutions", "solution/3/ES"),
    Child2("EN", "Environmental Studies \nSolutions", "solution/3/ENS"),
    Child2("H", "Hindi Solutions", "solution/3/HIS"),
  ],
  [
    Child2("M", "Maths Solutions", "solution/2/MS"),
    Child2("E", "English Solutions", "solution/2/ES"),
    Child2("H", "Hindi Solutions", "solution/2/HIS"),
  ],
  [
    Child2("M", "Maths Solutions", "solution/1/MS"),
    Child2("E", "English Solutions", "solution/1/ES"),
  ],
];

List notesChildrenList = [
  [
    Child2("P", "Physics(XII)", "notes/12/PN"),
    Child2("M", "MATHS(XII)", "notes/12/MN"),
    Child2("C", "Chemistry(XII)", "notes/12/CN"),
    Child2("B", "Biology(XII)", "notes/12/BN"),
    Child2("E", "English(XII)", "notes/12/EN"),
    Child2("BS", "Business Studies(XII)", "notes/12/BSN"),
    Child2("CS", "C++(XII)", "notes/12/CSN"),
    Child2("E", "Micro & Macro \nEconomics(XII)", "notes/12/ECN"),
    Child2("E", "Indian Economics(XII)", "notes/12/IEN"),
    Child2("G", "Geography(XII)", "notes/12/GEN"),
    Child2("H", "History(XII)", "notes/12/HIN"),
    Child2("IP", "Information Practices(XII)", "notes/12/IPN"),
    Child2("P", "Physical Education(XII)", "notes/12/PHN"),
    Child2("PS", "Political Science(XII)", "notes/12/PON"),
    Child2("S", "Sociology(XII)", "notes/12/SN"),
  ],
  [
    Child2("P", "Physics(XI)", "notes/11/PN"),
    Child2("M", "Maths(XI)", "notes/11/MN"),
    Child2("C", "Chemistry(XI)", "notes/11/CN"),
    Child2("B", "Biology(XI)", "notes/11/BN"),
    Child2("E", "English(XI)", "notes/11/EN"),
    Child2("BS", "Business Studies(XI)", "notes/11/BSN"),
    Child2("CS", "Computer Science(XI)", "notes/11/CSN"),
    Child2("E", "Indian Economic Development(XI)", "notes/11/EN"),
    Child2("G", "Geography(XI)", "notes/11/GN"),
    Child2("H", "History(XI)", "notes/11/HN"),
    Child2("IP", "Information Practices(XI)", "notes/11/IPN"),
    Child2("P", "Physical Education(XI)", "notes/11/PHN"),
    Child2("PS", "Political Science(XI)", "notes/11/PLN"),
    Child2("S", "Sociology(XI)", "notes/11/SN"),
    Child2("A", "Accountancy(XI)", "notes/11/AN")
  ],
  [
    Child2("C", "Civics(X)", "notes/10/CN"),
    Child2("E", "Economics(X)", "notes/10/CN"),
    Child2("E", "English(X)", "notes/10/EN"),
    Child2("G", "Geography(X)", "notes/10/GN"),
    Child2("H", "History(X)", "notes/10/HN"),
    Child2("M", "Maths(X)", "notes/10/MN"),
    Child2("S", "Science(X)", "notes/10/CSN"),
  ],
  [
    Child2("PS", "Political Science(IX)", "notes/9/CN"),
    Child2("E", "Economics(IX)", "notes/9/CN"),
    Child2("E", "English(IX)", "notes/9/EN"),
    Child2("G", "Geography(IX)", "notes/9/GN"),
    Child2("H", "History(IX)", "notes/9/HN"),
    Child2("M", "Maths(IX)", "notes/9/MN"),
    Child2("S", "Science(IX)", "notes/9/CSN"),
  ],
  [
    Child2("C", "Civics(VIII)", "notes/8/CN"),
    Child2("G", "Geography(VIII)", "notes/8/GN"),
    Child2("H", "History(VIII)", "notes/8/HN"),
    Child2("M", "Maths(VIII)", "notes/8/MN"),
    Child2("S", "Science(VIII)", "notes/8/CSN"),
  ],
  [
    Child2("C", "Civics(VII)", "notes/7/CN"),
    Child2("G", "Geography(VII)", "notes/7/GN"),
    Child2("H", "History(VII)", "notes/7/HN"),
    Child2("M", "Maths(VII)", "notes/7/MN"),
    Child2("S", "Science(VII)", "notes/7/CSN"),
  ],
  [
    Child2("C", "Civics(VI)", "notes/6/CN"),
    Child2("G", "Geography(VI)", "notes/6/GN"),
    Child2("H", "History(VI)", "notes/6/HN"),
    Child2("M", "Maths(VI)", "notes/6/MN"),
    Child2("S", "Science(VI)", "notes/6/CSN"),
  ],
];
List vediosChildrenList = [
  [
    Child2("M", "Maths", "vedios/JEE/MV"),
    Child2("P", "Physics", "vedios/JEE/PV"),
    Child2("C", "Chemistry", "vedios/JEE/CV"),
    Child2("A", "Aptitude", "vedios/JEE/AV")
  ],
  [
    Child2("B", "Biology", "vedios/JEE/BV"),
    Child2("P", "Physics", "vedios/JEE/PV"),
    Child2("C", "Chemistry", "vedios/JEE/CV"),
  ],
  [
    Child2("P", "Physics(XII)", "vedios/10/PV"),
    Child2("M", "Maths(XII)", "vedios/10/MV"),
    Child2("C", "Chemistry(XII)", "vedios/10/CV"),
    Child2("B", "Biology(XII)", "vedios/10/Bv"),
    Child2("E", "English(XII)", "vedios/10/EV"),
    Child2("BS", "Business Studies(XII)", "vedios/10/BSV"),
    Child2("CS", "Computer Science(XII)", "vedios/10/CSV"),
    Child2("E", " Economics(XII)", "vedios/10/EV"),
    Child2("G", "Geography(XII)", "vedios/10/GV"),
    Child2("H", "History(XII)", "vedios/10/HV"),
    Child2("IP", "Information Practices(XII)", "vedios/10/IPV"),
    Child2("P", "Accountancy (XII)", "vedios/10/AV"),
    Child2("PS", "Political Science(XII)", "vedios/10/PLV"),
    Child2("S", "Sociology(XII)", "vedios/10/SV"),
    Child2("A", "Accountancy(XII)", "vedios/10/AV")
  ],
  [
    Child2("P", "Physics(XI)", "vedios/11/PV"),
    Child2("M", "Maths(XI)", "vedios/11/MV"),
    Child2("C", "Chemistry(XI)", "vedios/11/CV"),
    Child2("B", "Biology(XI)", "vedios/11/BV"),
    Child2("E", "English(XI)", "vedios/11/EV"),
    Child2("BS", "Business Studies(XI)", "vedios/11/BSV"),
    Child2("CS", "Computer Science(XI)", "vedios/11/CSV"),
    Child2("E", " Economic (XI)", "vedios/11/EV"),
    Child2("G", "Geography(XI)", "vedios/11/GV"),
    Child2("H", "History(XI)", "vedios/11/HV"),
    Child2("IP", "Information Practices(XI)", "vedios/11/IPV"),
    Child2("P", "Physical Education(XI)", "vedios/11/PHV"),
    Child2("PS", "Political Science(XI)", "vedios/11/PLV"),
    Child2("S", "Sociology(XI)", "vedios/11/SV"),
    Child2("A", "Accountancy(XI)", "vedios/11/AV")
  ],
  [
    Child2("M", "Maths Solutions", "vedios/10/MV"),
    Child2("S", " Science ", "vedios/10/SV"),
    Child2("E", "English ", "vedios/10/EV"),
    Child2("ST", "Social Studies ", "vedios/10/SV"),
    Child2("H", "Hindi ", "vedios/10/HIV"),
    Child2("S", "Sanskrit ", "vedios/10/SNV"),
    Child2("CS", "Computer", "vedios/10/CSV")
  ],
  [
    Child2("M", "Maths Solutions", "vedios/9/MV"),
    Child2("S", " Science ", "vedios/9/SV"),
    Child2("E", "English ", "vedios/9/EV"),
    Child2("ST", "Social Studies", "vedios/9/SV"),
    Child2("H", "Hindi ", "vedios/9/HIV"),
    Child2("S", "Sanskrit ", "vedios/9/SNV"),
    Child2("CS", "Computer", "vedios/9/CSV")
  ],
  [
    Child2("M", "Maths Solutions", "vedios/8/MV"),
    Child2("S", " Science ", "vedios/8/SV"),
    Child2("E", "English ", "vedios/8/EV"),
    Child2("ST", "Social Studies", "vedios/8/SV"),
    Child2("H", "Hindi ", "vedios/8/HIV"),
    Child2("S", "Sanskrit ", "vedios/8/SNV"),
    Child2("CS", "Computer", "vedios/8/CSV")
  ],
  [
    Child2("M", "Maths Solutions", "vedios/8/MV"),
    Child2("S", " Science ", "vedios/8/SV"),
    Child2("E", "English ", "vedios/8/EV"),
    Child2("ST", "Social Studies", "vedios/8/SV"),
    Child2("H", "Hindi ", "vedios/8/HIV"),
    Child2("S", "Sanskrit ", "vedios/8/SNV"),
    Child2("CS", "Computer", "vedios/8/CSV")
  ],
  [
    Child2("M", "Maths Solutions", "vedios/7/MV"),
    Child2("S", " Science ", "vedios/7/SV"),
    Child2("E", "English ", "vedios/7/EV"),
    Child2("ST", "Social Studies", "vedios/7/SV"),
    Child2("H", "Hindi ", "vedios/7/HIV"),
    Child2("S", "Sanskrit ", "vedios/7/SNV"),
    Child2("CS", "Computer", "vedios/7/CSV")
  ],
  [
    Child2("M", "Maths Solutions", "vedios/6/MV"),
    Child2("S", " Science ", "vedios/6/SV"),
    Child2("E", "English ", "vedios/6/EV"),
    Child2("ST", "Social Studies", "vedios/6/SV"),
    Child2("H", "Hindi ", "vedios/6/HIV"),
    Child2("S", "Sanskrit ", "vedios/6/SNV"),
    Child2("CS", "Computer", "vedios/6/CSV")
  ],
  [
    Child2("M", "Maths Solutions", "vedios/5/MV"),
    Child2("E", "English ", "vedios/5/EV"),
    Child2("E", " Environmental", "vedios/5/EV"),
    Child2("H", "Hindi ", "vedios/5/HIV"),
  ],
  [
    Child2("M", "Maths Solutions", "vedios/4/MV"),
    Child2("E", "English ", "vedios/4/EV"),
    Child2("E", " Environmental", "vedios/4/EV"),
    Child2("H", "Hindi ", "vedios/4/HIV"),
  ],
  [
    Child2("M", "Maths Solutions", "vedios/3/MV"),
    Child2("E", "English ", "vedios/3/EV"),
    Child2("E", " Environmental", "vedios/3/EV"),
    Child2("H", "Hindi ", "vedios/3/HIV"),
  ],
  [
    Child2("M", "Maths Solutions", "vedios/2/MV"),
    Child2("E", "English ", "vedios/2/EV"),
    Child2("E", " Environmental", "vedios/2/EV"),
    Child2("H", "Hindi ", "vedios/2/HIV"),
  ],
  [
    Child2("M", "Maths Solutions", "vedios/5/MV"),
    Child2("E", "English ", "vedios/5/EV"),
    Child2("E", " Environmental", "vedios/5/EV"),
    Child2("H", "Hindi ", "vedios/5/HIV"),
  ],
];
List papersChildrenList = [
  [
    Child2("A", "Accountancy(XII)", "paper/12/AP"),
    Child2("B", "Biology(XII)", "paper/12/BP"),
    Child2("BS", "Business Studies(XII)", "paper/12/BSP"),
    Child2("C", "Chemistry(XII)", "paper/12/CP"),
    Child2("CS", "Computer(XII)", "paper/12/CSP"),
    Child2("E", " Economics(XII)", "paper/12/IEP"),
    Child2("E", "English(XII)", "paper/12/EP"),
    Child2("G", "Geography(XII)", "paper/12/GEP"),
    Child2("H", "Hindi(XII)", "paper/12/HP"),
    Child2("H", "History(XII)", "paper/12/HIP"),
    Child2("M", "MATHS(XII)", "paper/12/MP"),
    Child2("P", "Physics(XII)", "paper/12/PP"),
    Child2("PS", "Political Science(XII)", "paper/12/POP"),
    Child2("P", "Physical Education(XII)", "paper/12/PHP"),
  ],
  [
    Child2("A", "Accountancy Sample(XI)", "paper/11/AP"),
    Child2("B", "Biology Sample(XI)", "paper/11/BP"),
    Child2("BS", "Business Studies Sample(XI)", "paper/11/BSP"),
    Child2("C", "Chemistry Sample(XI)", "paper/11/CP"),
    Child2("CS", "Computer Sample(XI)", "paper/11/CSP"),
    Child2("E", " Economics Sample(XI)", "paper/11/IEP"),
    Child2("E", "English Sample(XI)", "paper/11/EP"),
    Child2("G", "Geography Sample(XI)", "paper/11/GEP"),
    Child2("H", "Hindi Sample(XI)", "paper/11/HP"),
    Child2("M", "MATHS Sample(XI)", "paper/11/MP"),
    Child2("P", "Physics Sample(XI)", "paper/11/PP"),
    Child2("PS", " Information Technologu\n Sample(XI)", "paper/11/POP"),
    Child2("P", " Sociology Sample(XI)", "paper/11/PHP"),
  ],
  [
    Child2("M", "Maths(X)", "paper/10/MP"),
    Child2("E", "English(X)", "paper/10/EP"),
    Child2("H", "Hindi(X)", "paper/10/HP"),
    Child2("ST", "Social(X)", "paper/10/SP"),
    Child2("S", "Science(X)", "paper/10/SIP"),
    Child2("S", "Sanskrit(X)", "paper/10/SKP"),
    Child2("F", "Fix(X)", "paper/10/FP"),
  ],
  [
    Child2("M", "Maths(XI)", "paper/9/MP"),
    Child2("E", "English(XI)", "paper/9/EP"),
    Child2("H", "Hindi(XI)", "paper/9/HP"),
    Child2("ST", "Social(XI)", "paper/9/SP"),
    Child2("S", "Science(XI)", "paper/9/SIP"),
  ],
  [
    Child2("M", "Maths(VIII)", "paper/8/MP"),
    Child2("H", "Hindi(VIII)", "paper/8/HP"),
    Child2("ST", "Socila(VIII)", "paper/8/SP"),
    Child2("S", "Science(VIII)", "paper/8/SIP"),
  ],
  [
    Child2("M", "Maths(VII)", "paper/7/MP"),
    Child2("H", "Hindi(VII)", "paper/7/HP"),
    Child2("S", "Science(VII)", "paper/7/SIP"),
  ],
  [
    Child2("M", "Maths(VI)", "paper/6/MP"),
    Child2("E", "English(VI)", "paper/6/EP"),
    Child2("H", "Hindi(VI)", "paper/6/HP"),
    Child2("ST", "Socila(VI)", "paper/6/SP"),
  ],
];

class Child2 {
  final String head;
  final String lable;
  final Color color = RandomColor().randomColor();
  final String url;

  Child2(this.head, this.lable, this.url);

  factory Child2.froJson(json) {
    return Child2(json['subject'][0].toString().toUpperCase(), json['subject'],
        json['url']);
  }
}

List<Child1> english = [
  Child1("12", "Class 12\nBooks", englishChildrenList[0]),
  Child1("11", "Class 11\nBooks", englishChildrenList[1]),
  Child1("10", "Class 10\nBooks", englishChildrenList[2]),
  Child1("9", "Class 9\nBooks", englishChildrenList[3]),
  Child1("8", "Class 8\nBooks", englishChildrenList[4]),
  Child1("7", "Class 7\nBooks", englishChildrenList[5]),
  Child1("6", "Class 6\nBooks", englishChildrenList[6]),
  Child1("5", "Class 5\nBooks", englishChildrenList[7]),
  Child1("4", "Class 4\nBooks", englishChildrenList[8]),
  Child1("3", "Class 3\nBooks", englishChildrenList[9]),
  Child1("2", "Class 2\nBooks", englishChildrenList[10]),
  Child1("1", "Class 1\nBooks", englishChildrenList[11]),
];

List<Child1> hindi = [
  Child1("12", "Class 12\nBooks", hindiChildrenList[0]),
  Child1("11", "Class 11\nBooks", hindiChildrenList[1]),
  Child1("10", "Class 10\nBooks", hindiChildrenList[2]),
  Child1("9", "Class 9\nBooks", hindiChildrenList[3]),
  Child1("8", "Class 8\nBooks", hindiChildrenList[4]),
  Child1("7", "Class 7\nBooks", hindiChildrenList[5]),
  Child1("6", "Class 6\nBooks", hindiChildrenList[6]),
  Child1("5", "Class 5\nBooks", hindiChildrenList[7]),
  Child1("4", "Class 4\nBooks", hindiChildrenList[8]),
  Child1("3", "Class 3\nBooks", hindiChildrenList[9]),
  Child1("2", "Class 2\nBooks", hindiChildrenList[10]),
  Child1("1", "Class 1\nBooks", hindiChildrenList[11]),
];

List<Child1> solutions = [
  Child1("RS", "RS Aggarwal\nSolutions", solutionsChildrenList[0]),
  Child1("RD", "RD Sharma\nSolutions", solutionsChildrenList[1]),
  Child1("HC", "HC Verma\nSolutions", solutionsChildrenList[2]),
  Child1("IE", "IE Idrodov\nSolutions", solutionsChildrenList[3]),
  Child1("Ls", "Lakhmir Singh\nSolutions", solutionsChildrenList[4]),
  Child1("TS", "TS Grewal\nSolutions", solutionsChildrenList[5]),
  Child1("12", "Class 12\nSolutions", solutionsChildrenList[6]),
  Child1("11", "Class 11\nSolutions", solutionsChildrenList[7]),
  Child1("10", "Class 10\nSolutions", solutionsChildrenList[8]),
  Child1("9", "Class 9\nSolutions", solutionsChildrenList[9]),
  Child1("8", "Class 8\nSolutions", solutionsChildrenList[10]),
  Child1("7", "Class 7\nSolutions", solutionsChildrenList[11]),
  Child1("6", "Class 6\nSolutions", solutionsChildrenList[12]),
  Child1("5", "Class 5\nSolutions", solutionsChildrenList[13]),
  Child1("4", "Class 4\nSolutions", solutionsChildrenList[14]),
  Child1("3", "Class 3\nSolutions", solutionsChildrenList[15]),
  Child1("2", "Class 2\nSolutions", solutionsChildrenList[16]),
  Child1("1", "Class 1\nSolutions", solutionsChildrenList[17]),
];

List<Child1> notes = [
  Child1("12", "Class 12\nBooks", notesChildrenList[0]),
  Child1("11", "Class 11\nBooks", notesChildrenList[1]),
  Child1("10", "Class 10\nBooks", notesChildrenList[2]),
  Child1("9", "Class 9\nBooks", notesChildrenList[3]),
  Child1("8", "Class 8\nBooks", notesChildrenList[4]),
  Child1("7", "Class 7\nBooks", notesChildrenList[5]),
  Child1("6", "Class 6\nBooks", notesChildrenList[6]),
];
List<Child1> vedios = [
  Child1("Ls", "JEE\nvideos", vediosChildrenList[0]),
  Child1("TS", "NEET\nvideos", vediosChildrenList[1]),
  Child1("12", "Class 12\nvideos", vediosChildrenList[2]),
  Child1("11", "Class 11\nvideos", vediosChildrenList[3]),
  Child1("10", "Class 10\nvideos", vediosChildrenList[4]),
  Child1("9", "Class 9\nvideos", vediosChildrenList[5]),
  Child1("8", "Class 8\nvideos", vediosChildrenList[6]),
  Child1("7", "Class 7\nvideos", vediosChildrenList[7]),
  Child1("6", "Class 6\nvideos", vediosChildrenList[8]),
  Child1("5", "Class 5\nvideos", vediosChildrenList[9]),
  Child1("4", "Class 4\nvideos", vediosChildrenList[10]),
  Child1("3", "Class 3\nvideos", vediosChildrenList[11]),
  Child1("2", "Class 2\nvideos", vediosChildrenList[12]),
  Child1("1", "Class 1\nvideos", vediosChildrenList[13]),
];
List<Child1> papers = [
  Child1("12", "Class 12\nSample Papers", papersChildrenList[0]),
  Child1("11", "Class 11\nSample Papers", papersChildrenList[1]),
  Child1("10", "Class 10\nSample Papers", papersChildrenList[2]),
  Child1("9", "Class 9\nSample Papers", papersChildrenList[3]),
  Child1("8", "Class 8\nSample Papers", papersChildrenList[4]),
  Child1("7", "Class 7\nSample Papers", papersChildrenList[5]),
  Child1("6", "Class 6\nSample Papers", papersChildrenList[6]),
];
List<Child1> quiz = [
  Child1("JE", "JEE Quiz", null),
  Child1("NT", "NEET Quiz", null),
  Child1("12", "Class 12 Quiz", null),
  Child1("11", "Class 11 Quiz", null),
  Child1("10", "Class 10 Quiz", null),
  Child1("9", "Class 9 Quiz", null),
  Child1("8", "Class 8 Quiz", null),
  Child1("7", "Class 7 Quiz", null),
  Child1("6", "Class 6 Quiz", null),
  Child1("5", "Class 5 Quiz", null),
  Child1("4", "Class 4 Quiz", null),
  Child1("3", "Class 3 Quiz", null),
  Child1("2", "Class 2 Quiz", null),
  Child1("1", "Class 1 Quiz", null),
];
